# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://app.vagrantup.com/bento
BOX_IMAGE = "bento/ubuntu-16.04"

Vagrant.configure("2") do |config|

  config.vm.box = BOX_IMAGE
  config.vm.hostname = "spark"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "hello spark"
  SHELL
end
