#!/bin/sh

echo "\nHostname: \033[1;31m$(hostname -s)\033[0m"
echo "Uptime:$(uptime)\n"
echo '* NameNode: http://172.16.0.10:50070'
echo '* ResourceManager: http://172.16.0.10:8088'
echo '* MapReduce Job History Server: http://172.16.0.10:19888'
