# -*- mode: ruby -*-
# vi: set ft=ruby :

DATA_PATH = ".data"
KEY_PATH = DATA_PATH + "/hadoop_rsa"

# https://app.vagrantup.com/bento
BOX_IMAGE = "bento/ubuntu-16.04"
NODE_COUNT = 3

VAGRANT_COMMAND = ARGV[0]
Vagrant.configure("2") do |config|

  config.vm.box = BOX_IMAGE

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = "hadoop"
    config.ssh.private_key_path = KEY_PATH
  end

  config.vm.define "master" do |node|
    node.vm.hostname = "master"
    node.vm.network "private_network", ip: "172.16.0.10"
    # NameNode
    node.vm.network "forwarded_port", guest: 50070, host: 50070
    # ResourceManager
    node.vm.network "forwarded_port", guest: 8088, host: 8088
    # MapReduce Job History server
    node.vm.network "forwarded_port", guest: 19888, host: 19888

    node.vm.synced_folder DATA_PATH + "/master", "/data"
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"
      node.vm.network :private_network, ip: "172.16.0.#{i + 100}"

      node.vm.synced_folder DATA_PATH + "/node-#{i}", "/data"
    end
  end

  config.vm.provision "shell", path: "./script/setup_ubuntu.sh"
  config.vm.provision "shell", path: "./script/setup_hadoop.sh"
  config.vm.provision "shell", path: "./script/bootstrap.sh", run: 'always'
end
