# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://app.vagrantup.com/bento
BOX_IMAGE = "bento/ubuntu-16.04"
NODE_COUNT = 3

DATA_PATH_HOST = ".data"
DATA_PATH_GUEST = "/vol"
KEY_PATH = DATA_PATH_HOST + "/hadoop_rsa"
HADOOP_ID = "1101"

VAGRANT_COMMAND = ARGV[0]
Vagrant.configure("2") do |config|

  config.vm.box = BOX_IMAGE

  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = "hadoop"
    config.ssh.private_key_path = KEY_PATH
  end

  config.vm.define "master" do |node|
    node.vm.hostname = "master"
    
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    node.vm.network "private_network", ip: "172.16.0.10"
    # NameNode
    node.vm.network "forwarded_port", guest: 50070, host: 50070
    # ResourceManager
    node.vm.network "forwarded_port", guest: 8088, host: 8088
    # MapReduce Job History server
    node.vm.network "forwarded_port", guest: 19888, host: 19888
    # Oozie
    node.vm.network "forwarded_port", guest: 11000, host: 11000

    # synced_folder permission issue https://github.com/hashicorp/vagrant/issues/936
    node.vm.synced_folder DATA_PATH_HOST + "/master", DATA_PATH_GUEST,
      mount_options: ["uid=" + HADOOP_ID, "gid=" + HADOOP_ID]
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end

      node.vm.network :private_network, ip: "172.16.0.#{i + 100}"

      node.vm.synced_folder DATA_PATH_HOST + "/node-#{i}", DATA_PATH_GUEST,
        mount_options: ["uid=" + HADOOP_ID, "gid=" + HADOOP_ID]
    end
  end

  config.vm.provision "shell", path: "./script/setup_ubuntu.sh"
  config.vm.provision "shell", path: "./script/setup_hadoop.sh"
  config.vm.provision "shell", path: "./script/setup_spark.sh"
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    su --login hadoop /vagrant/script/bootstrap.sh
  SHELL
end
