# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://app.vagrantup.com/bento
BOX_IMAGE = "bento/ubuntu-16.04"
NODE_COUNT = 3
DATA_PATH = "data/"

VAGRANT_COMMAND = ARGV[0]
Vagrant.configure("2") do |config|

  config.vm.box = BOX_IMAGE

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = 'hadoop'
    config.ssh.private_key_path = "./data/hadoop_rsa"
  end

  config.vm.define "namenode" do |node|
    node.vm.hostname = "namenode"
    node.vm.network "private_network", ip: "172.16.0.10"
    node.vm.network "forwarded_port", guest: 50070, host: 50070

    node.vm.synced_folder DATA_PATH, "/namenode"
  end

  config.vm.define "resource-manager" do |node|
    node.vm.hostname = "resource-manager"
    node.vm.network "private_network", ip: "172.16.0.11"
    node.vm.network "forwarded_port", guest: 8088, host: 8088
    node.vm.network "forwarded_port", guest: 19888, host: 19888

    node.vm.synced_folder DATA_PATH, "/resource-manager"
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"
      node.vm.network :private_network, ip: "172.16.0.#{i + 100}"

      node.vm.synced_folder DATA_PATH + "node-#{i}", "/data"
    end
  end

  #config.vm.provision "shell", path: "./script/setup_all.sh"
  #config.vm.provision "shell", path: "./script/bootstrap.sh", run: 'always'
end
