# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "ubuntu/bionic64"
NODE_COUNT = 3
PATH_SHARE = ".share"

Vagrant.configure("2") do |config|

  config.vm.box = BOX_IMAGE

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "192.168.100.10"
    ansible.vm.synced_folder ENV['HOME'], "/local"
    ansible.vm.provision "file", source: PATH_SHARE + "/ssh/ansible_rsa", destination: "$HOME/.ssh/id_rsa"
    ansible.vm.provision "shell", path: "setup_ansible.sh"
    ansible.vm.synced_folder "data/", "/ansible"
    ansible.vm.provision "shell", inline: <<-SHELL
      # default syncronized inventory
      ln -sf /ansible/hosts /etc/ansible/hosts
    SHELL
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "ip-192-168-100-#{i + 10}"
      node.vm.network :private_network, ip: "192.168.100.#{i + 10}"
      node.vm.synced_folder PATH_SHARE + "/node-#{i}", "/data"
    end
  end

  # give ssh access to each machine
  config.vm.provision "file", source: PATH_SHARE + "/ssh/ansible_rsa.pub", destination: "/tmp/ansible_rsa.pub"
  config.vm.provision "shell", inline: <<-SHELL
    # append ansible key to avoid lose vagrant key with copy
    cat /tmp/ansible_rsa.pub >> .ssh/authorized_keys
    rm /tmp/ansible_rsa.pub
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    # update
    apt-get update
    # required python2 missing on ubuntu-18
    apt-get install -y python2.7 python-pip
    # dns
    apt-get install -y avahi-daemon libnss-mdns 
  SHELL
end
