name: github-pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # TODO updated fork https://github.com/andi34/mkdocs-deploy-gh-pages/tree/nomaterial
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
